In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
from scipy.stats import shapiro,wilcoxon,ttest_1samp,ttest_ind,ttest_rel


# Chi-Square Tests

### Case 1


In [2]:
M=pd.read_csv('Migraine.csv')
CT=pd.crosstab(M['hatype'],M['Gender'])
CT #contigency table

Gender   female  male
hatype               
Aura       1593   117
Mixed       291   166
No Aura    1661   324

In [8]:
CT['female'].sum()

3545

In [9]:
CT.loc['Aura'].sum()

1710

In [5]:
M.shape[0] #grand total 

4152

In [6]:
ec1=(CT['female'].sum()*CT.loc['Aura'].sum())/M.shape[0]
ec2=(CT['female'].sum()*CT.loc['Mixed'].sum())/M.shape[0]
ec3=(CT['female'].sum()*CT.loc['No Aura'].sum())/M.shape[0]

In [7]:
ec1,ec2,ec3

(1460.007225433526, 390.1890655105973, 1694.8037090558767)

In [10]:
ec4=(CT['male'].sum()*CT.loc['Aura'].sum())/M.shape[0]
ec5=(CT['male'].sum()*CT.loc['Mixed'].sum())/M.shape[0]
ec6=(CT['male'].sum()*CT.loc['No Aura'].sum())/M.shape[0]

In [11]:
ec4,ec5,ec6

(249.992774566474, 66.8109344894027, 290.1962909441233)

In [12]:
#Female manual caluclation - to check propotions percentage %

PFA=1593/3545  #propotion of Female having Aura
PFM=291/3545   #propotion of Female having Migraine
PFNA=1661/3545 #propotion of Female having No Aura
PFA,PFM,PFNA

(0.44936530324400564, 0.08208744710860366, 0.4685472496473907)

In [13]:
#Male manual caluclations - to check propotions percentage %

PMA=117/607
PMM=166/607
PMNA=324/607
PMA,PMM,PMNA

(0.1927512355848435, 0.27347611202635913, 0.5337726523887973)

In [ ]:
#propotions are not same definitely Ho will be rejected and Ha will be accepted but we need to prove statistically also.
#so far we have compared only numerically

In [14]:
oc=np.array([1593,291,1661,117,166,324])
ec=np.array([ec1,ec2,ec3,ec4,ec5,ec6])


In [15]:
CT

Gender   female  male
hatype               
Aura       1593   117
Mixed       291   166
No Aura    1661   324

In [16]:
#Manual formula
chi_sq=np.sum((oc-ec)**2/ec)
chi_sq

259.94962922327386

In [18]:
from scipy.stats import chi2_contingency


In [19]:
#Funtion method
chi2_contingency(CT)

(259.94962922327386,
 3.569893234435195e-57,
 2,
 array([[1460.00722543,  249.99277457],
        [ 390.18906551,   66.81093449],
        [1694.80370906,  290.19629094]]))

In [ ]:
#For expected count the propotions of Male and Female are equal. If value were like this for original count and then we 
#caluclated expected count then we can say like Ho holds good bcoz propotions are same.
#Example given by sir to explain to us when will be accpet Ho.

#Expected Count
PFA=1460/3545
PFM=390/3545
PFNA=1695/3545
PFA,PFM,PFNA

In [ ]:
#Expected Count
PMA=250/607
PMM=67/607
PMNA=290/607
PMA,PMM,PMNA

### Case 2

The table below contains the number of perfect, satisfactory and defective products are manufactured by both male and female.

| Gender  | Perfect | Satisfactory | Defective |
| ------- | ---- | --------- | -------- |
| Male    | 138 | 83 | 64 |
| Female  | 64 | 67 | 84 |


Question : Do these data provide sufficient evidence at the 5% significance level to infer that there are differences in quality among genders (Male and Female)?

In [ ]:
#if it was given as pandas dataframe then consider it like pandas and use pd.crosstab()
#But table itself is given so we pass in 2-D array using np

In [21]:
quality_array = np.array([[138, 83, 64],[64, 67, 84]]) #observed count of male,observed count of female
chi_sq_Stat, p_value, deg_freedom, exp_freq = stats.chi2_contingency(quality_array)

print('Chi-square statistic %3.5f P value %1.6f Degrees of freedom %d' %(chi_sq_Stat, p_value,deg_freedom))

Chi-square statistic 22.15247 P value 0.000015 Degrees of freedom 2


In [29]:
chi2_contingency(quality_array)

(22.152468645918482,
 1.547578021398957e-05,
 2,
 array([[115.14,  85.5 ,  84.36],
        [ 86.86,  64.5 ,  63.64]]))

In [ ]:
Post hoc analysis

In [23]:
138/(138+83+64) #male perfect 

0.4842105263157895

In [24]:
64/(138+83+64) #male defetive 

0.22456140350877193

In [25]:
64/(64+67+84) #female perfect 

0.29767441860465116

In [26]:
84/(64+67+84) #female defetive 

0.39069767441860465

## Chi-Square - One factor

###  Case 1


A1 airlines operated daily flights to several Indian cities. The operations manager believes that 30% of their passengers prefer vegan food, 45% prefer vegetarian food , 20% prefer non-veg food 5% request for Jain food. 

A sample of 500 passengers was chosen to analyse the food preferences and the data is shown in the following table:

|               | Food type | Vegan | Vegetarian | Non-Vegetarian | Jain |
| ------------------------- | ---- | ---- | ----- | ---- | ---- |
|Number of passengers |  | 190 | 185 | 90 | 35 |

At 5% level of significance, can you confirm that the meal preference is as per the belief of the operations manager?

In [27]:
import scipy.stats as stats
import scipy

observed_values    = scipy.array([190, 185, 90, 35])
n                  = observed_values.sum()

expected_values    = scipy.array([n*0.3, n*.45, n*0.2, n*0.05]) #150,225,100,25

chi_square_stat, p_value = stats.chisquare(observed_values, f_exp=expected_values)

print('At 5 %s level of significance, the p-value is %1.7f' %('%', p_value))

print('At 5 %s level of significance, the chi observed is %1.7f' %('%', chi_square_stat))

## chi critical at 95% is 8.907


At 5 % level of significance, the p-value is 0.0000449
At 5 % level of significance, the chi observed is 22.7777778


E:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  after removing the cwd from sys.path.
E:\Anaconda\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  import sys


In [ ]:
# Note : When sample rejects Ho then we go for another round for a different sample to check if it still rejects.
# Maybe like 300 records or 700 records like that. Again if it rejects the multiple sample again and again then 
# We need to infer that maybe our Hypothesis assumptions which could be wrong 
# i.e Expecations is wrong whicf also means that expecatations less than 30% and not 30% for example.

In [ ]:
#Extra doing as per expectations manager expecations. Manually changing values to somewhat nearby expected values 
#Then we are performing the test

In [28]:
observed_values    = scipy.array([155, 200, 95, 30])
n                  = observed_values.sum()

expected_values    = scipy.array([n*0.3, n*.45, n*0.2, n*0.05])

chi_square_stat, p_value = stats.chisquare(observed_values, f_exp=expected_values)

print('At 5 %s level of significance, the p-value is %1.7f' %('%', p_value))

print('At 5 %s level of significance, the chi observed is %1.7f' %('%', chi_square_stat))

At 5 % level of significance, the p-value is 0.3161384
At 5 % level of significance, the chi observed is 3.5358796


E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  """Entry point for launching an IPython kernel.
E:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  after removing the cwd from sys.path.


In [ ]:
#Extra which i did. More the pvalue is closer to 1 we can say the sample is more reliable.

In [30]:
observed_values    = scipy.array([151, 200, 100, 25])
n                  = observed_values.sum()

expected_values    = scipy.array([n*0.3, n*.45, n*0.2, n*0.05])

chi_square_stat, p_value = stats.chisquare(observed_values, f_exp=expected_values)

print('At 5 %s level of significance, the p-value is %1.7f' %('%', p_value))

print('At 5 %s level of significance, the chi observed is %1.7f' %('%', chi_square_stat))

At 5 % level of significance, the p-value is 0.6336590
At 5 % level of significance, the chi observed is 1.7147526


E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  """Entry point for launching an IPython kernel.
E:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  after removing the cwd from sys.path.


### chisquare methods using HR dataset 

In [33]:
A=pd.read_table('HR.txt',index_col=0)
A.head(2)

Attrition  Age  BusinessTravel  DailyRate  Department  \
Individual                                                          
Ind1              Yes   41               1       1102           1   
Ind2               No   49               2        279           2   

             DistanceFromHome  Education  EducationField  EmployeeCount  \
Individual                                                                
Ind1                        1          2               1              1   
Ind2                        8          1               1              1   

             EmployeeNumber  ...  RelationshipSatisfaction  StandardHours  \
Individual                   ...                                            
Ind1                      1  ...                         1             80   
Ind2                      2  ...                         4             80   

             StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
Individual                                                                
Ind1                        0                  8                      0   
Ind2                        1                 10                      3   

             WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
Individual                                                         
Ind1                       1               6                   4   
Ind2                       3              10                   7   

             YearsSinceLastPromotion  YearsWithCurrManager  
Individual                                                  
Ind1                               0                     5  
Ind2                               1                     7  

[2 rows x 34 columns]

In [34]:
#Grp 2

CT=pd.crosstab(A['Attrition'],A['Education'])
CT

Education    1    2    3    4   5
Attrition                        
No         139  238  473  340  43
Yes         31   44   99   58   5

In [47]:
x=np.array(CT.loc['Yes'])
x

array([31, 44, 99, 58,  5], dtype=int64)

In [48]:
n=np.array(CT.sum())
n

array([170, 282, 572, 398,  48], dtype=int64)

In [50]:
x=np.array([31,44,99,58,5])
n=np.array([170,282,472,398,48])

In [51]:
from scipy.stats import chi2_contingency
chi2_contingency(CT)

(3.0739613982367193,
 0.5455253376565949,
 4,
 array([[142.59183673, 236.53469388, 479.77959184, 333.83265306,
          40.26122449],
        [ 27.40816327,  45.46530612,  92.22040816,  64.16734694,
           7.73877551]]))

In [53]:
#Grp 1

CT2=pd.crosstab(A['Attrition'],A['Department'])
CT2

Department    1    2   3
Attrition               
No          354  828  51
Yes          92  133  12

In [54]:
chi2_contingency(CT2)


(10.79600732241067,
 0.004525606574479633,
 2,
 array([[374.09387755, 806.06326531,  52.84285714],
        [ 71.90612245, 154.93673469,  10.15714286]]))

In [55]:
#Grp3
CT3=pd.crosstab(A['Attrition'],A['MaritalStatus'])
CT3

MaritalStatus    1    2    3
Attrition                   
No             350  589  294
Yes            120   84   33

In [56]:
chi2_contingency(CT3)

(46.163676540848705,
 9.45551106034083e-11,
 2,
 array([[394.2244898 , 564.49591837, 274.27959184],
        [ 75.7755102 , 108.50408163,  52.72040816]]))

In [18]:
homework=pd.read_csv('fair_pay_data.csv')
homework

employee_id   department        salary new_hire job_level
0               1        Sales  103263.63550       No  Salaried
1               2  Engineering   80708.64104       No    Hourly
2               4  Engineering   60737.04786      Yes    Hourly
3               5  Engineering   99116.32328      Yes  Salaried
4               7  Engineering   51021.64386       No    Hourly
...           ...          ...           ...      ...       ...
1465         2061  Engineering   49384.53146       No    Hourly
1466         2062  Engineering   78588.46832      Yes    Hourly
1467         2064  Engineering   87528.24317       No  Salaried
1468         2065        Sales   67971.31922       No    Hourly
1469         2068  Engineering   63652.14172       No    Hourly

[1470 rows x 5 columns]

In [27]:
homework_ct=pd.crosstab(homework['new_hire'],homework['department'])
homework_ct

department  Engineering  Finance  Sales
new_hire                               
No                  701       46    325
Yes                 260       17    121

In [25]:
from scipy.stats import chi2_contingency

In [26]:
chi2_contingency(homework_ct)

(0.0011396558895788336,
 0.9994303343763208,
 2,
 array([[700.81088435,  45.94285714, 325.2462585 ],
        [260.18911565,  17.05714286, 120.7537415 ]]))

In [ ]:
0.9994303343763208>0.05. which means we can reject the  Null hypothesis.
so hiring is not related to education

In [29]:
homework_ct.iloc[1,0]

260